const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/image/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: '5',
      numReviews: '10K',
      description: 'very good shirt',
    },
    {
      name: 'Adidas slim shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirt',
      image: '/image/p2.jpg',
      price: 165,
      countInStock: 120,
      brand: 'Adidas',
      rating: '5',
      numReviews: '210K',
      description: 'very good shirt',
    },
    {
      name: 'Nike slim pant',
      slug: 'nike-slim-pant',
      category: 'Pant',
      image: '/image/p3.jpg',
      price: 25,
      countInStock: 160,
      brand: 'Nike',
      rating: '5',
      numReviews: '12K',
      description: 'very nice cloth',
    },
    {
      name: 'Adidas slim pant',
      slug: 'adidas-slim-pant',
      category: 'Pant',
      image: '/image/p4.jpg',
      price: 65,
      countInStock: 120,
      brand: 'Adidas',
      rating: '5',
      numReviews: '20K',
      description: 'very nice pant',
    },
  ],
};
export default data;
